-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\OFDM_Rx_HW\ofdm_rx_src_ToComplex1_block.vhd
-- Created: 2022-03-24 22:06:16
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ofdm_rx_src_ToComplex1_block
-- Source Path: OFDM_Rx_HW/OFDMRx/PhaseTracking_2/PilotCtrlGen/pilotGen/ToComplex1
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ofdm_rx_src_ToComplex1_block IS
  PORT( In1                               :   IN    std_logic_vector(1 DOWNTO 0);  -- sfix2
        Out1_re                           :   OUT   std_logic_vector(1 DOWNTO 0);  -- sfix2
        Out1_im                           :   OUT   std_logic_vector(1 DOWNTO 0)  -- sfix2
        );
END ofdm_rx_src_ToComplex1_block;


ARCHITECTURE rtl OF ofdm_rx_src_ToComplex1_block IS

  -- Signals
  SIGNAL Constant1_out1                   : signed(1 DOWNTO 0);  -- sfix2

BEGIN
  Constant1_out1 <= to_signed(16#0#, 2);

  Out1_im <= std_logic_vector(Constant1_out1);

  Out1_re <= In1;

END rtl;

