-- -------------------------------------------------------------
-- 
-- File Name: C:\Git\rfsoc_ofdm\boards\ip\models\hdl_prj\OFDM_rx\hdlsrc\OFDM_Rx_HW\ofdm_rx_src_ThreshMult.vhd
-- Created: 2021-02-25 17:36:53
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ofdm_rx_src_ThreshMult
-- Source Path: OFDM_Rx_HW/OFDMRx/Synchronisation/SchmidlCoxMetric /ThreshMult
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ofdm_rx_src_ThreshMult IS
  PORT( In1                               :   IN    std_logic_vector(35 DOWNTO 0);  -- sfix36_En30
        Out1                              :   OUT   std_logic_vector(32 DOWNTO 0)  -- sfix33_En23
        );
END ofdm_rx_src_ThreshMult;


ARCHITECTURE rtl OF ofdm_rx_src_ThreshMult IS

  -- Signals
  SIGNAL In1_signed                       : signed(35 DOWNTO 0);  -- sfix36_En30
  SIGNAL ThreshMult_cast                  : signed(71 DOWNTO 0);  -- sfix72_En65
  SIGNAL ThreshMult_out1                  : signed(32 DOWNTO 0);  -- sfix33_En23

BEGIN
  In1_signed <= signed(In1);

  ThreshMult_cast <= resize(In1_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 72);
  ThreshMult_out1 <= resize(ThreshMult_cast(71 DOWNTO 42), 33);

  Out1 <= std_logic_vector(ThreshMult_out1);

END rtl;

