-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\OFDM_Rx_HW\ofdm_rx_src_CIC_MA.vhd
-- Created: 2022-03-24 22:06:16
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ofdm_rx_src_CIC_MA
-- Source Path: OFDM_Rx_HW/OFDMRx/PhaseTracking_2/PhaseEst/CIC_MA
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.ofdm_rx_src_OFDMRx_pkg.ALL;

ENTITY ofdm_rx_src_CIC_MA IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_12_0                        :   IN    std_logic;
        In1_re                            :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        In1_im                            :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        Out1_re                           :   OUT   std_logic_vector(22 DOWNTO 0);  -- sfix23_En15
        Out1_im                           :   OUT   std_logic_vector(22 DOWNTO 0)  -- sfix23_En15
        );
END ofdm_rx_src_CIC_MA;


ARCHITECTURE rtl OF ofdm_rx_src_CIC_MA IS

  -- Signals
  SIGNAL In1_re_signed                    : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL In1_im_signed                    : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Delay1_reg_re                    : vector_of_signed18(0 TO 3);  -- sfix18_En15 [4]
  SIGNAL Delay1_reg_im                    : vector_of_signed18(0 TO 3);  -- sfix18_En15 [4]
  SIGNAL Delay1_out1_re                   : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Delay1_out1_im                   : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Add_sub_cast                     : signed(22 DOWNTO 0);  -- sfix23_En15
  SIGNAL Add_sub_cast_1                   : signed(22 DOWNTO 0);  -- sfix23_En15
  SIGNAL Add_sub_cast_2                   : signed(22 DOWNTO 0);  -- sfix23_En15
  SIGNAL Add_sub_cast_3                   : signed(22 DOWNTO 0);  -- sfix23_En15
  SIGNAL Add_out1_re                      : signed(22 DOWNTO 0);  -- sfix23_En15
  SIGNAL Add_out1_im                      : signed(22 DOWNTO 0);  -- sfix23_En15
  SIGNAL Delay2_out1_re                   : signed(22 DOWNTO 0);  -- sfix23_En15
  SIGNAL Delay2_out1_im                   : signed(22 DOWNTO 0);  -- sfix23_En15
  SIGNAL Add1_out1_re                     : signed(22 DOWNTO 0);  -- sfix23_En15
  SIGNAL Add1_out1_im                     : signed(22 DOWNTO 0);  -- sfix23_En15

BEGIN
  In1_re_signed <= signed(In1_re);

  In1_im_signed <= signed(In1_im);

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_reg_re <= (OTHERS => to_signed(16#00000#, 18));
      Delay1_reg_im <= (OTHERS => to_signed(16#00000#, 18));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_12_0 = '1' THEN
        Delay1_reg_im(0) <= In1_im_signed;
        Delay1_reg_im(1 TO 3) <= Delay1_reg_im(0 TO 2);
        Delay1_reg_re(0) <= In1_re_signed;
        Delay1_reg_re(1 TO 3) <= Delay1_reg_re(0 TO 2);
      END IF;
    END IF;
  END PROCESS Delay1_process;

  Delay1_out1_re <= Delay1_reg_re(3);
  Delay1_out1_im <= Delay1_reg_im(3);

  Add_sub_cast <= resize(In1_re_signed, 23);
  Add_sub_cast_1 <= resize(Delay1_out1_re, 23);
  Add_out1_re <= Add_sub_cast - Add_sub_cast_1;
  Add_sub_cast_2 <= resize(In1_im_signed, 23);
  Add_sub_cast_3 <= resize(Delay1_out1_im, 23);
  Add_out1_im <= Add_sub_cast_2 - Add_sub_cast_3;

  Add1_out1_re <= Delay2_out1_re + Add_out1_re;
  Add1_out1_im <= Delay2_out1_im + Add_out1_im;

  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_out1_re <= to_signed(16#000000#, 23);
      Delay2_out1_im <= to_signed(16#000000#, 23);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_12_0 = '1' THEN
        Delay2_out1_re <= Add1_out1_re;
        Delay2_out1_im <= Add1_out1_im;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  Out1_re <= std_logic_vector(Delay2_out1_re);

  Out1_im <= std_logic_vector(Delay2_out1_im);

END rtl;

