-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\OFDM_rx\hdlsrc\OFDM_Tx_Rx_HW\ofdm_rx_src_PilotEq.vhd
-- Created: 2021-01-08 12:41:57
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ofdm_rx_src_PilotEq
-- Source Path: OFDM_Tx_Rx_HW/OFDMRx/PhaseTracking_1/GradientEstimate /PilotEq
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.ofdm_rx_src_OFDMRx_pkg.ALL;

ENTITY ofdm_rx_src_PilotEq IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_192_0                       :   IN    std_logic;
        In1_re                            :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        In1_im                            :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        In2_re                            :   IN    std_logic_vector(1 DOWNTO 0);  -- sfix2
        In2_im                            :   IN    std_logic_vector(1 DOWNTO 0);  -- sfix2
        Out1_re                           :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        Out1_im                           :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En15
        );
END ofdm_rx_src_PilotEq;


ARCHITECTURE rtl OF ofdm_rx_src_PilotEq IS

  -- Signals
  SIGNAL In1_re_signed                    : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL In1_im_signed                    : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Delay2_out1_re                   : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Delay2_out1_im                   : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL In2_re_signed                    : signed(1 DOWNTO 0);  -- sfix2
  SIGNAL In2_im_signed                    : signed(1 DOWNTO 0);  -- sfix2
  SIGNAL Delay3_out1_re                   : signed(1 DOWNTO 0);  -- sfix2
  SIGNAL Delay3_out1_im                   : signed(1 DOWNTO 0);  -- sfix2
  SIGNAL reduced_reg                      : vector_of_signed2(0 TO 39);  -- sfix2 [40]
  SIGNAL Product_C2ReIm_2_C2ReIm_A        : signed(1 DOWNTO 0);  -- sfix2
  SIGNAL Product_mul_temp                 : signed(19 DOWNTO 0);  -- sfix20_En15
  SIGNAL Product_Re_AC                    : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Product_Re_AC_1                  : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL reduced_reg_1                    : vector_of_signed2(0 TO 39);  -- sfix2 [40]
  SIGNAL Product_C2ReIm_2_C2ReIm_B        : signed(1 DOWNTO 0);  -- sfix2
  SIGNAL Product2_mul_temp                : signed(19 DOWNTO 0);  -- sfix20_En15
  SIGNAL Product_Re_BD                    : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Product_Re_BD_1                  : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL mulOutput                        : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Product1_mul_temp                : signed(19 DOWNTO 0);  -- sfix20_En15
  SIGNAL Product_Im_AD                    : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Product_Im_AD_1                  : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Product3_mul_temp                : signed(19 DOWNTO 0);  -- sfix20_En15
  SIGNAL Product_Im_BC                    : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Product_Im_BC_1                  : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL mulOutput_1                      : signed(17 DOWNTO 0);  -- sfix18_En15

BEGIN
  In1_re_signed <= signed(In1_re);

  In1_im_signed <= signed(In1_im);

  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_out1_re <= to_signed(16#00000#, 18);
      Delay2_out1_im <= to_signed(16#00000#, 18);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_192_0 = '1' THEN
        Delay2_out1_re <= In1_re_signed;
        Delay2_out1_im <= In1_im_signed;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  In2_re_signed <= signed(In2_re);

  In2_im_signed <= signed(In2_im);

  Delay3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay3_out1_re <= to_signed(16#0#, 2);
      Delay3_out1_im <= to_signed(16#0#, 2);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_192_0 = '1' THEN
        Delay3_out1_re <= In2_re_signed;
        Delay3_out1_im <= In2_im_signed;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  reduced_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      reduced_reg <= (OTHERS => to_signed(16#0#, 2));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_192_0 = '1' THEN
        reduced_reg(0) <= Delay3_out1_re;
        reduced_reg(1 TO 39) <= reduced_reg(0 TO 38);
      END IF;
    END IF;
  END PROCESS reduced_process;

  Product_C2ReIm_2_C2ReIm_A <= reduced_reg(39);

  Product_mul_temp <= Delay2_out1_re * Product_C2ReIm_2_C2ReIm_A;
  Product_Re_AC <= Product_mul_temp(17 DOWNTO 0);

  PipelineRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Product_Re_AC_1 <= to_signed(16#00000#, 18);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_192_0 = '1' THEN
        Product_Re_AC_1 <= Product_Re_AC;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  reduced_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      reduced_reg_1 <= (OTHERS => to_signed(16#0#, 2));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_192_0 = '1' THEN
        reduced_reg_1(0) <= Delay3_out1_im;
        reduced_reg_1(1 TO 39) <= reduced_reg_1(0 TO 38);
      END IF;
    END IF;
  END PROCESS reduced_1_process;

  Product_C2ReIm_2_C2ReIm_B <= reduced_reg_1(39);

  Product2_mul_temp <= Delay2_out1_im * Product_C2ReIm_2_C2ReIm_B;
  Product_Re_BD <= Product2_mul_temp(17 DOWNTO 0);

  PipelineRegister2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Product_Re_BD_1 <= to_signed(16#00000#, 18);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_192_0 = '1' THEN
        Product_Re_BD_1 <= Product_Re_BD;
      END IF;
    END IF;
  END PROCESS PipelineRegister2_process;


  mulOutput <= Product_Re_AC_1 - Product_Re_BD_1;

  Out1_re <= std_logic_vector(mulOutput);

  Product1_mul_temp <= Delay2_out1_re * Product_C2ReIm_2_C2ReIm_B;
  Product_Im_AD <= Product1_mul_temp(17 DOWNTO 0);

  PipelineRegister1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Product_Im_AD_1 <= to_signed(16#00000#, 18);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_192_0 = '1' THEN
        Product_Im_AD_1 <= Product_Im_AD;
      END IF;
    END IF;
  END PROCESS PipelineRegister1_process;


  Product3_mul_temp <= Delay2_out1_im * Product_C2ReIm_2_C2ReIm_A;
  Product_Im_BC <= Product3_mul_temp(17 DOWNTO 0);

  PipelineRegister3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Product_Im_BC_1 <= to_signed(16#00000#, 18);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_192_0 = '1' THEN
        Product_Im_BC_1 <= Product_Im_BC;
      END IF;
    END IF;
  END PROCESS PipelineRegister3_process;


  mulOutput_1 <= Product_Im_AD_1 + Product_Im_BC_1;

  Out1_im <= std_logic_vector(mulOutput_1);

END rtl;

