-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\OFDM_tx\hdlsrc\OFDM_Tx_Rx_HW\ofdm_tx_src_BPSKmap.vhd
-- Created: 2021-01-14 13:09:24
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ofdm_tx_src_BPSKmap
-- Source Path: OFDM_Tx_Rx_HW/OFDMTx/DataGenerator/SymbolsGen/BPSKmap
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.ofdm_tx_src_OFDMTx_pkg.ALL;

ENTITY ofdm_tx_src_BPSKmap IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_192_0                       :   IN    std_logic;
        bits                              :   IN    std_logic;
        validIn                           :   IN    std_logic;
        BPSKOut_re                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        BPSKOut_im                        :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
        );
END ofdm_tx_src_BPSKmap;


ARCHITECTURE rtl OF ofdm_tx_src_BPSKmap IS

  -- Signals
  SIGNAL Constant4_out1_re                : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Constant4_out1_im                : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Constant_out1_re                 : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Constant_out1_im                 : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Constant1_out1_re                : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Constant1_out1_im                : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Multiport_Switch_out1_re         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Multiport_Switch_out1_im         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL delayMatch_reg_re                : vector_of_signed16(0 TO 1);  -- sfix16_En14 [2]
  SIGNAL delayMatch_reg_im                : vector_of_signed16(0 TO 1);  -- sfix16_En14 [2]
  SIGNAL Multiport_Switch_out1_re_1       : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Multiport_Switch_out1_im_1       : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Switch_out1_re                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Switch_out1_im                   : signed(15 DOWNTO 0);  -- sfix16_En14

BEGIN
  Constant4_out1_re <= to_signed(16#0000#, 16);
  Constant4_out1_im <= to_signed(16#0000#, 16);

  Constant_out1_re <= to_signed(-16#4000#, 16);
  Constant_out1_im <= to_signed(16#0000#, 16);

  Constant1_out1_re <= to_signed(16#4000#, 16);
  Constant1_out1_im <= to_signed(16#0000#, 16);

  
  Multiport_Switch_out1_re <= Constant_out1_re WHEN bits = '0' ELSE
      Constant1_out1_re;
  
  Multiport_Switch_out1_im <= Constant_out1_im WHEN bits = '0' ELSE
      Constant1_out1_im;

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_re <= (OTHERS => to_signed(16#0000#, 16));
      delayMatch_reg_im <= (OTHERS => to_signed(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_192_0 = '1' THEN
        delayMatch_reg_im(0) <= Multiport_Switch_out1_im;
        delayMatch_reg_im(1) <= delayMatch_reg_im(0);
        delayMatch_reg_re(0) <= Multiport_Switch_out1_re;
        delayMatch_reg_re(1) <= delayMatch_reg_re(0);
      END IF;
    END IF;
  END PROCESS delayMatch_process;

  Multiport_Switch_out1_re_1 <= delayMatch_reg_re(1);
  Multiport_Switch_out1_im_1 <= delayMatch_reg_im(1);

  
  Switch_out1_re <= Constant4_out1_re WHEN validIn = '0' ELSE
      Multiport_Switch_out1_re_1;
  
  Switch_out1_im <= Constant4_out1_im WHEN validIn = '0' ELSE
      Multiport_Switch_out1_im_1;

  BPSKOut_re <= std_logic_vector(Switch_out1_re);

  BPSKOut_im <= std_logic_vector(Switch_out1_im);

END rtl;

