-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\data_inspector\hdlsrc\OFDM_Tx_Rx_HW\data_inspector_src_data_inspector_pkg.vhd
-- Created: 2021-01-08 12:51:53
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE data_inspector_src_data_inspector_pkg IS
  TYPE T_controlModeType IS (None, init, fill_frame, idle1, update, dma_read, idle);
END data_inspector_src_data_inspector_pkg;

