-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\data_inspector\hdlsrc\OFDM_Tx_Rx_HW\data_inspector_src_data_inspector.vhd
-- Created: 2021-01-08 12:51:53
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 5.20833e-09
-- Target subsystem base rate: 1e-06
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1e-06
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- m_axis_re_tdata               ce_out        1e-06
-- m_axis_re_tvalid              ce_out        1e-06
-- m_axis_im_tdata               ce_out        1e-06
-- m_axis_im_tvalid              ce_out        1e-06
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: data_inspector_src_data_inspector
-- Source Path: OFDM_Tx_Rx_HW/data_inspector
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY data_inspector_src_data_inspector IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        frame_size                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        s_axis_re_tdata                   :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        s_axis_re_tvalid                  :   IN    std_logic;
        s_axis_im_tdata                   :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        s_axis_im_tvalid                  :   IN    std_logic;
        m_axis_tready                     :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        m_axis_re_tdata                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        m_axis_re_tvalid                  :   OUT   std_logic;
        m_axis_im_tdata                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        m_axis_im_tvalid                  :   OUT   std_logic
        );
END data_inspector_src_data_inspector;


ARCHITECTURE rtl OF data_inspector_src_data_inspector IS

  -- Component Declarations
  COMPONENT data_inspector_src_control
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_192_0                     :   IN    std_logic;
          dma_tready                      :   IN    std_logic;
          frame_size                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          rx_tvalid                       :   IN    std_logic;
          push                            :   OUT   std_logic;
          pop                             :   OUT   std_logic;
          out_tvalid                      :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT data_inspector_src_HDL_FIFO
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_192_0                     :   IN    std_logic;
          In_re                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          In_im                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          Push                            :   IN    std_logic;
          Pop                             :   IN    std_logic;
          Out_re                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          Out_im                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          Empty                           :   OUT   std_logic;
          Full                            :   OUT   std_logic;
          Num                             :   OUT   std_logic_vector(11 DOWNTO 0)  -- ufix12
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : data_inspector_src_control
    USE ENTITY work.data_inspector_src_control(rtl);

  FOR ALL : data_inspector_src_HDL_FIFO
    USE ENTITY work.data_inspector_src_HDL_FIFO(rtl);

  -- Signals
  SIGNAL enb_1_192_0                      : std_logic;
  SIGNAL s_axis_re_tdata_signed           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL s_axis_im_tdata_signed           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay1_out1_re                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay1_out1_im                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL AND2_out1                        : std_logic;
  SIGNAL push                             : std_logic;
  SIGNAL pop                              : std_logic;
  SIGNAL out_tvalid                       : std_logic;
  SIGNAL HDL_FIFO_out2                    : std_logic;
  SIGNAL NOT_out1                         : std_logic;
  SIGNAL AND_out1                         : std_logic;
  SIGNAL HDL_FIFO_out3                    : std_logic;
  SIGNAL NOT1_out1                        : std_logic;
  SIGNAL AND1_out1                        : std_logic;
  SIGNAL HDL_FIFO_out1_re                 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL HDL_FIFO_out1_im                 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL HDL_FIFO_out4                    : std_logic_vector(11 DOWNTO 0);  -- ufix12
  SIGNAL Delay2_out1                      : std_logic;

BEGIN
  u_control : data_inspector_src_control
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_192_0 => clk_enable,
              dma_tready => m_axis_tready,
              frame_size => frame_size,  -- uint32
              rx_tvalid => AND2_out1,
              push => push,
              pop => pop,
              out_tvalid => out_tvalid
              );

  u_HDL_FIFO : data_inspector_src_HDL_FIFO
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_192_0 => clk_enable,
              In_re => std_logic_vector(Delay1_out1_re),  -- sfix16_En14
              In_im => std_logic_vector(Delay1_out1_im),  -- sfix16_En14
              Push => AND1_out1,
              Pop => AND_out1,
              Out_re => HDL_FIFO_out1_re,  -- sfix16_En14
              Out_im => HDL_FIFO_out1_im,  -- sfix16_En14
              Empty => HDL_FIFO_out2,
              Full => HDL_FIFO_out3,
              Num => HDL_FIFO_out4  -- ufix12
              );

  s_axis_re_tdata_signed <= signed(s_axis_re_tdata);

  s_axis_im_tdata_signed <= signed(s_axis_im_tdata);

  enb_1_192_0 <= clk_enable;

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_out1_re <= to_signed(16#0000#, 16);
      Delay1_out1_im <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_192_0 = '1' THEN
        Delay1_out1_re <= s_axis_re_tdata_signed;
        Delay1_out1_im <= s_axis_im_tdata_signed;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  AND2_out1 <= s_axis_re_tvalid AND s_axis_im_tvalid;

  NOT_out1 <=  NOT HDL_FIFO_out2;

  AND_out1 <= pop AND NOT_out1;

  NOT1_out1 <=  NOT HDL_FIFO_out3;

  AND1_out1 <= push AND NOT1_out1;

  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_192_0 = '1' THEN
        Delay2_out1 <= out_tvalid;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  ce_out <= clk_enable;

  m_axis_re_tdata <= HDL_FIFO_out1_re;

  m_axis_re_tvalid <= Delay2_out1;

  m_axis_im_tdata <= HDL_FIFO_out1_im;

  m_axis_im_tvalid <= Delay2_out1;

END rtl;

