-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\OFDM_Tx_HW\ofdm_tx_src_OFDMTx_tc.vhd
-- Created: 2021-05-05 22:15:54
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ofdm_tx_src_OFDMTx_tc
-- Source Path: OFDMTx_tc
-- Hierarchy Level: 1
-- 
-- Master clock enable input: clk_enable
-- 
-- enb         : identical to clk_enable
-- enb_1_256_0 : 256x slower than clk with last phase
-- enb_1_256_1 : 256x slower than clk with phase 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ofdm_tx_src_OFDMTx_tc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        enb                               :   OUT   std_logic;
        enb_1_256_0                       :   OUT   std_logic;
        enb_1_256_1                       :   OUT   std_logic
        );
END ofdm_tx_src_OFDMTx_tc;


ARCHITECTURE rtl OF ofdm_tx_src_OFDMTx_tc IS

  -- Signals
  SIGNAL count256                         : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL phase_all                        : std_logic;
  SIGNAL phase_0                          : std_logic;
  SIGNAL phase_0_tmp                      : std_logic;
  SIGNAL phase_1                          : std_logic;
  SIGNAL phase_1_tmp                      : std_logic;

BEGIN
  Counter256 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      count256 <= to_unsigned(1, 8);
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        IF count256 >= to_unsigned(255, 8) THEN
          count256 <= to_unsigned(0, 8);
        ELSE
          count256 <= count256 + to_unsigned(1, 8);
        END IF;
      END IF;
    END IF; 
  END PROCESS Counter256;

  phase_all <= '1' WHEN clk_enable = '1' ELSE '0';

  temp_process1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      phase_0 <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        phase_0 <= phase_0_tmp;
      END IF;
    END IF; 
  END PROCESS temp_process1;

  phase_0_tmp <= '1' WHEN count256 = to_unsigned(255, 8) AND clk_enable = '1' ELSE '0';

  temp_process2 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      phase_1 <= '1';
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        phase_1 <= phase_1_tmp;
      END IF;
    END IF; 
  END PROCESS temp_process2;

  phase_1_tmp <= '1' WHEN count256 = to_unsigned(0, 8) AND clk_enable = '1' ELSE '0';

  enb <=  phase_all AND clk_enable;

  enb_1_256_0 <=  phase_0 AND clk_enable;

  enb_1_256_1 <=  phase_1 AND clk_enable;


END rtl;

