-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\OFDM_Tx_HW\ofdm_tx_src_preambIFFTValid.vhd
-- Created: 2022-03-24 21:51:00
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ofdm_tx_src_preambIFFTValid
-- Source Path: OFDM_Tx_HW/OFDMTx/IFFT/IFFTValid/preambIFFTValid
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ofdm_tx_src_preambIFFTValid IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_12_0                        :   IN    std_logic;
        preambValid                       :   IN    std_logic;
        preambIFFTValidOut                :   OUT   std_logic
        );
END ofdm_tx_src_preambIFFTValid;


ARCHITECTURE rtl OF ofdm_tx_src_preambIFFTValid IS

  -- Signals
  SIGNAL NOT_out1                         : std_logic;
  SIGNAL HDL_Counter1_out1                : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Compare_To_Constant1_out1        : std_logic;
  SIGNAL Compare_To_Constant2_out1        : std_logic;
  SIGNAL AND_out1                         : std_logic;
  SIGNAL AND1_out1                        : std_logic;
  SIGNAL Compare_To_Constant3_out1        : std_logic;
  SIGNAL Compare_To_Constant4_out1        : std_logic;
  SIGNAL AND2_out1                        : std_logic;
  SIGNAL AND3_out1                        : std_logic;
  SIGNAL OR_out1                          : std_logic;

BEGIN
  NOT_out1 <=  NOT preambValid;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 319
  HDL_Counter1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter1_out1 <= to_unsigned(16#000#, 9);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_12_0 = '1' THEN
        IF NOT_out1 = '1' THEN 
          HDL_Counter1_out1 <= to_unsigned(16#000#, 9);
        ELSIF preambValid = '1' THEN 
          IF HDL_Counter1_out1 >= to_unsigned(16#13F#, 9) THEN 
            HDL_Counter1_out1 <= to_unsigned(16#000#, 9);
          ELSE 
            HDL_Counter1_out1 <= HDL_Counter1_out1 + to_unsigned(16#001#, 9);
          END IF;
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter1_process;


  
  Compare_To_Constant1_out1 <= '1' WHEN HDL_Counter1_out1 >= to_unsigned(16#060#, 9) ELSE
      '0';

  
  Compare_To_Constant2_out1 <= '1' WHEN HDL_Counter1_out1 <= to_unsigned(16#09F#, 9) ELSE
      '0';

  AND_out1 <= Compare_To_Constant1_out1 AND Compare_To_Constant2_out1;

  AND1_out1 <= AND_out1 AND preambValid;

  
  Compare_To_Constant3_out1 <= '1' WHEN HDL_Counter1_out1 >= to_unsigned(16#100#, 9) ELSE
      '0';

  
  Compare_To_Constant4_out1 <= '1' WHEN HDL_Counter1_out1 <= to_unsigned(16#13F#, 9) ELSE
      '0';

  AND2_out1 <= Compare_To_Constant3_out1 AND Compare_To_Constant4_out1;

  AND3_out1 <= AND2_out1 AND preambValid;

  OR_out1 <= AND1_out1 OR AND3_out1;

  preambIFFTValidOut <= OR_out1;

END rtl;

