-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\OFDM_Tx_HW\ofdm_tx_src_STSFreq.vhd
-- Created: 2022-03-24 21:51:00
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ofdm_tx_src_STSFreq
-- Source Path: OFDM_Tx_HW/OFDMTx/DataGenerator/STSFreq
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.ofdm_tx_src_OFDMTx_pkg.ALL;

ENTITY ofdm_tx_src_STSFreq IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_12_0                        :   IN    std_logic;
        enb_1_12_1                        :   IN    std_logic;
        enb                               :   IN    std_logic;
        preamVal                          :   IN    std_logic;
        stsFreq_re                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        stsFreq_im                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        stsVal                            :   OUT   std_logic
        );
END ofdm_tx_src_STSFreq;


ARCHITECTURE rtl OF ofdm_tx_src_STSFreq IS

  -- Constants
  CONSTANT t2_re                          : vector_of_signed16(0 TO 63) := 
    (to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(-16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(-16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(-16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(-16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(-16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16));  -- sfix16 [64]
  CONSTANT t2_im                          : vector_of_signed16(0 TO 63) := 
    (to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(-16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(-16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(-16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(-16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(-16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#4000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16));  -- sfix16 [64]

  -- Signals
  SIGNAL NOT_out1                         : std_logic;
  SIGNAL HDL_Counter1_out1                : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL HDL_Counter1_out1_1              : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Compare_To_Constant_out1         : std_logic;
  SIGNAL Compare_To_Constant1_out1        : std_logic;
  SIGNAL AND_out1                         : std_logic;
  SIGNAL preamVal_1                       : std_logic;
  SIGNAL AND1_out1                        : std_logic;
  SIGNAL HDL_Counter2_bypass_reg          : std_logic;  -- ufix1
  SIGNAL AND1_out1_1                      : std_logic;
  SIGNAL HDL_Counter_out1                 : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL HDL_Counter_out1_1               : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL STSFreq_k                        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL STSFreq_out1_re                  : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL STSFreq_out1_im                  : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL STSFreq_out1_re_1                : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16_En14
  SIGNAL STSFreq_out1_im_1                : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16_En14

BEGIN
  NOT_out1 <=  NOT preamVal;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 319
  HDL_Counter1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter1_out1 <= to_unsigned(16#000#, 9);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_12_0 = '1' THEN
        IF NOT_out1 = '1' THEN 
          HDL_Counter1_out1 <= to_unsigned(16#000#, 9);
        ELSIF preamVal = '1' THEN 
          IF HDL_Counter1_out1 >= to_unsigned(16#13F#, 9) THEN 
            HDL_Counter1_out1 <= to_unsigned(16#000#, 9);
          ELSE 
            HDL_Counter1_out1 <= HDL_Counter1_out1 + to_unsigned(16#001#, 9);
          END IF;
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter1_process;


  HDL_Counter1_out1_1 <= HDL_Counter1_out1;

  
  Compare_To_Constant_out1 <= '1' WHEN HDL_Counter1_out1_1 >= to_unsigned(16#060#, 9) ELSE
      '0';

  
  Compare_To_Constant1_out1 <= '1' WHEN HDL_Counter1_out1_1 <= to_unsigned(16#09F#, 9) ELSE
      '0';

  AND_out1 <= Compare_To_Constant_out1 AND Compare_To_Constant1_out1;

  preamVal_1 <= preamVal;

  AND1_out1 <= AND_out1 AND preamVal_1;

  HDL_Counter2_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter2_bypass_reg <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_12_1 = '1' THEN
        HDL_Counter2_bypass_reg <= AND1_out1;
      END IF;
    END IF;
  END PROCESS HDL_Counter2_bypass_process;

  
  AND1_out1_1 <= AND1_out1 WHEN enb_1_12_1 = '1' ELSE
      HDL_Counter2_bypass_reg;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 63
  HDL_Counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter_out1 <= to_unsigned(16#00#, 6);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_12_0 = '1' AND AND1_out1_1 = '1' THEN
        HDL_Counter_out1 <= HDL_Counter_out1 + to_unsigned(16#01#, 6);
      END IF;
    END IF;
  END PROCESS HDL_Counter_process;


  HDL_Counter_out1_1 <= HDL_Counter_out1;

  
  STSFreq_k <= to_unsigned(16#00#, 6) WHEN HDL_Counter_out1_1 = to_unsigned(16#00#, 6) ELSE
      to_unsigned(16#3F#, 6) WHEN HDL_Counter_out1_1 = to_unsigned(16#3F#, 6) ELSE
      HDL_Counter_out1_1;
  STSFreq_out1_re <= t2_re(to_integer(STSFreq_k));
  STSFreq_out1_im <= t2_im(to_integer(STSFreq_k));

  PipelineRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        STSFreq_out1_re_1 <= STSFreq_out1_re;
        STSFreq_out1_im_1 <= STSFreq_out1_im;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  stsFreq_re <= std_logic_vector(STSFreq_out1_re_1);

  stsFreq_im <= std_logic_vector(STSFreq_out1_im_1);

  stsVal <= AND1_out1;

END rtl;

