-- -------------------------------------------------------------
-- 
-- File Name: C:\Git\rfsoc_ofdm_workspace\models\hdl_prj\data_inspector\hdlsrc\data_inspector_test\data_inspector_src_data_inspector_pkg.vhd
-- Created: 2021-02-02 18:10:40
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE data_inspector_src_data_inspector_pkg IS
  TYPE T_controlModeType IS (None, init, fill_frame, idle1, update, dma_read, dma_tlast, idle2, idle);
END data_inspector_src_data_inspector_pkg;

