-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\OFDM_tx\hdlsrc\OFDM_Tx_Rx_HW\ofdm_tx_src_DataGenBPSK.vhd
-- Created: 2021-01-08 12:14:22
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ofdm_tx_src_DataGenBPSK
-- Source Path: OFDM_Tx_Rx_HW/OFDMTx/DataGenerator/SymbolsGen/DataGenBPSK
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ofdm_tx_src_DataGenBPSK IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_192_0                       :   IN    std_logic;
        y                                 :   OUT   std_logic
        );
END ofdm_tx_src_DataGenBPSK;


ARCHITECTURE rtl OF ofdm_tx_src_DataGenBPSK IS

  -- Component Declarations
  COMPONENT ofdm_tx_src_PN_Sequence_Generator
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_192_0                     :   IN    std_logic;
          PN_Sequence                     :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : ofdm_tx_src_PN_Sequence_Generator
    USE ENTITY work.ofdm_tx_src_PN_Sequence_Generator(rtl);

  -- Signals
  SIGNAL PN_Sequence_Generator_out1       : std_logic;

BEGIN
  u_PN_Sequence_Generator : ofdm_tx_src_PN_Sequence_Generator
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_192_0 => enb_1_192_0,
              PN_Sequence => PN_Sequence_Generator_out1
              );

  y <= PN_Sequence_Generator_out1;

END rtl;

